---
- name: Check if Rust toolchain is installed
  ansible.builtin.stat:
    path: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/cargo"
  register: cargo_installed

- name: Install stable Rust toolchain
  ansible.builtin.command:
    cmd: rustup default stable
  when: not cargo_installed.stat.exists

- name: Install Cargo crates
  community.general.cargo:
    executable: "{{ item.executable | default(omit) }}"
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
  environment:
    PATH: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin:{{ ansible_facts['env']['PATH'] }}"
  loop: "{{ rust_crates }}"
  when: rust_crates is defined and rust_crates | length > 0
