---
- name: Get installed Rust toolchains
  ansible.builtin.command:
    cmd: rustup toolchain list
  environment:
    PATH: "{{ homebrew_prefix }}/opt/rustup/bin:{{ homebrew_prefix }}/bin:{{ ansible_facts['env']['PATH'] }}"
  register: rustup_toolchains
  changed_when: false

- name: Install and set default stable Rust toolchain
  ansible.builtin.command:
    cmd: rustup default stable
  environment:
    PATH: "{{ homebrew_prefix }}/opt/rustup/bin:{{ homebrew_prefix }}/bin:{{ ansible_facts['env']['PATH'] }}"
  when: "'stable' not in rustup_toolchains.stdout"

- name: Install Cargo crates
  community.general.cargo:
    executable: "{{ item.executable | default(omit) }}"
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
  environment:
    PATH: "{{ homebrew_prefix }}/opt/rustup/bin:{{ ansible_facts['env']['PATH'] }}"
  loop: "{{ rust_crates }}"
  when: rust_crates is defined and rust_crates | length > 0
