---
- name: Check if stable Rust toolchain is installed
  ansible.builtin.command:
    cmd: rustup toolchain list
  register: rustup_toolchains
  changed_when: false
  failed_when: false

- name: Install stable Rust toolchain
  ansible.builtin.command:
    cmd: rustup default stable
  when: "'stable' not in rustup_toolchains.stdout"

- name: Install Cargo crates
  community.general.cargo:
    executable: "{{ item.executable | default(omit) }}"
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
  environment:
    PATH: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin:{{ ansible_facts['env']['PATH'] }}"
  loop: "{{ rust_crates }}"
  when: rust_crates is defined and rust_crates | length > 0
