---
configure_dotfiles: true

dotfiles_repo: https://github.com/nurodev/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .codex/AGENTS.md

  - .config/bat/config

  - .config/btop/btop.conf

  - .config/ghostty/config
  - .config/ghostty/themes/orng-dark
  - .config/ghostty/themes/orng-light

  - .config/opencode/INSTRUCTIONS.md
  - .config/opencode/opencode.jsonc

  - .config/zsh/aliases/ansible.zsh
  - .config/zsh/aliases/cargo.zsh
  - .config/zsh/aliases/containers.zsh
  - .config/zsh/aliases/deno.zsh
  - .config/zsh/aliases/homebrew.zsh
  - .config/zsh/aliases/misc.zsh
  - .config/zsh/aliases/nodejs.zsh
  - .config/zsh/envs.zsh
  - .config/zsh/functions.zsh
  - .config/zsh/init.zsh
  - .config/zsh/shell.zsh

  - .fet
  - .gitconfig
  - .gitignore
  - .nanorc
  - .nirc
  - .osx
  - .zshrc
