---
fnm_npm_global_packages:
  - name: "@antfu/ni"
  - name: "@anthropic-ai/claude-code"
  - name: "@mariozechner/pi-coding-agent"
  - name: cf
  - name: corepack
  - name: jsr
  - name: npm
  - name: opencode-ai
  - name: pnpm
  - name: workerd
  - name: wrangler

fnm_nodejs_versions:
  - "lts-latest"
