---
vite_plus_global_packages:
  - name: "@antfu/ni"
  - name: "@anthropic-ai/claude-code"
  - name: cf
  - name: jsr
  - name: opencode-ai
  - name: workerd
  - name: wrangler

vite_plus_nodejs_version: latest
