---
users:
  - username: "{{ ansible_facts['user_id'] }}"

oh_my_zsh_install: true
oh_my_zsh_write_zshrc: false
oh_my_zsh_update_mode: reminder
oh_my_zsh_plugins:
  - zsh-autosuggestions
  - zsh-completions
  - zsh-history-substring-search
  - zsh-syntax-highlighting
